import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App22',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="px-20">
      <h2 className="mt-2 rounded-2xl border-2 border-solid border-amber-950 bg-amber-400 text-center text-8xl font-semibold">
        layout form
      </h2>
      {children}
    </div>
  );
}
